name: "P4SDE CI Build pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: storage-ci-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build_p4dpdk_ubuntu:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          path: p4-sde
      - name: 'Install dependencies'
        working-directory: /tools/setup
        run: python install_dep.py
      - name: 'Compile p4sde dpdk target'
        working-directory: ./build/storage/tests/ut
        run: |
          PWD=$pwd
          export SDE=$PWD
          export SDE_INSTALL=$SDE/install
          mkdir -p $SDE_INSTALL
          echo $SDE
          echo $SDE_INSTALL
          cd $SDE/p4-sde
          ./autogen.sh
          ./configure --prefix=$SDE_INSTALL --enable-mev
          make -j4
          make install
