name: "P4SDE CI Build pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: storage-ci-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build_p4dpdk_ubuntu:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
             submodules: 'recursive'
      - name: 'Install dependencies'
        working-directory: ./tools/setup
        run: python install_dep.py
      - name: 'Compile p4sde dpdk target'
        run: |
              mkdir ${GITHUB_WORKSPACE}/install
              bash build-p4sde.sh -s ${GITHUB_WORKSPACE}/install -d
